### ISSUE TITLE
Cyberpunk My rewards don't unlock.

### ISSUE THREAD

**Issue by Bitwolfies** [imLinguin/comet#11]
Still says to launch using galaxy 2.0 to receive the unlocks.

(Does get the expansion working though, did you know that comet is the only way to play the gog version with the dlc right now? The game crashes if the galaxy services dlls are present, and without them the dlc doesnt appear, they drm'd it! So thanks for letting me play)

**Comment by imLinguin** [comment]
Having GOG Galaxy running in the background is also a solution

**Comment by imLinguin** [comment]
Do you have any comet log to share indicating not implemented calls etc...?

**Comment by somebody1121** [comment]
With 2.0 happens the same, but the rewards are unlocked, i have started a new game and i have them. The ones i don't have are from the dlc (maybe it gets unlock when the dlc stars). The only thing that is failing it's the menu.

**Comment by imLinguin** [comment]
Looks like it's either broken in the game or they made weird `REDLauncher <-> GOG Galaxy` integration, so Galaxy would need to be installed in the same prefix. Let's wait for first hotfix before judging

**Comment by imLinguin** [comment]
After RED Account migration everything should be managed by REDLauncher, even for latest GOG builds. That said features like "My rewards" and cross platform saves are not out of scope of comet.
