### ISSUE TITLE
Witcher 3 "My rewards" section require gog galaxy

### ISSUE THREAD

**Issue by karaushu** [imLinguin/comet#14]
Hi, have some issues with My Rewards in Witcher 3. I want to use [cross progression](https://support.cdprojektred.com/en/witcher-3/nintendo-switch/sp-technical/issue/2431/how-to-use-cross-progression-2) for switch/PC. When enter My rewards, there is a banner - "Open GOG Galaxy 2.0 and start the game". 
I downlaod Heroic (MacOS), installed the game.
Before launch: `comet --token <token>  --refresh-token <token>. --user-id <user>`
Logs seems fine, but i can't access my rewards section.
```
Accepting connection
INFO:handler:handle_message:Header 1|3
INFO:notification_pusher:handling_connection:started
INFO:notification_pusher:notification_message:2|2
INFO:notification_pusher:subscribing to chat, presence, friends
INFO:handler:handle_auth_request:authenticated the user <user>
INFO:handler:handle_message:responded with 1|4
INFO:handler:handle_message:Header 2|3
INFO:handler:handle_subscribe_topic:stub:friends
INFO:handler:handle_message:responded with 2|4
INFO:notification_pusher:notification_message:2|4
INFO:notification_pusher:subscribed_to:chat
INFO:handler:handle_message:Header 2|3
INFO:handler:handle_subscribe_topic:stub:presence
INFO:handler:handle_message:responded with 2|4
INFO:notification_pusher:notification_message:2|4
INFO:notification_pusher:subscribed_to:presence
INFO:handler:handle_message:Header 2|3
INFO:handler:handle_subscribe_topic:stub:chat
INFO:handler:handle_message:responded with 2|4
INFO:notification_pusher:notification_message:2|4
INFO:notification_pusher:subscribed_to:friends
INFO:handler:handle_message:Header 1|15
INFO:handler:handle_message:responded with 1|16
INFO:handler:handle_message:Header 1|23
INFO:handler:handle_message:responded with 1|24
```
Thanks, for such amazing tools!

**Comment by imLinguin** [comment]
They might've changed how the cross progression behaves. I'll try to track the issue down while I'm re-writing comet in Rust. I believe Cyberpunk 2077 will work similarly.

On a side note. As a workaround you can just run MacOS native GOG Galaxy in the background (yes it will work even if the game is running in Wine)

**Comment by karaushu** [comment]
Thank you for your time! 
Unfortunately, it did not help, same result.

**Comment by karaushu** [comment]
@imLinguin HI. hope you are doing well!
Just FYI that CD Projekt RED [anounce account migration ](https://support.cdprojektred.com/en/cdpr-accounts/account/cdpr-accounts/issue/2608/cd-projekt-red-account-migration-faq).

**Comment by imLinguin** [comment]
Quick update on this, turns out migration made it possible to obtain My Rewards without having GOG Galaxy.
I tested with Cyberpunk 2077, basically on first launch of the REDLauncher users are prompted to login

**Comment by karaushu** [comment]
Hi, thanks, as i know REDLauncher didn't works on MacOS, do you run it on Linux?
I will try it and will let you know. (JFYI)

**Comment by imLinguin** [comment]
Yes I run all that on Linux.  
Keep in mind that until now, it also used REDLauncher to launch the game, it was trying to read GOG Galaxy database in order to pick up it's login session (pretty bad design decision for secondary launcher if you ask me).
However it used to work in headless mode. Now after the migration it runs in normal mode for GOG versions (both Witcher 3 and Cyberpunk 2077) and doesn't attempt to read Galaxy, it just prompts to login to the RED account.

**Comment by karaushu** [comment]
So i just downloaded Witcher 3 (and also Cyberpunk 2077) from GOG vua Heroic. And there is no REDLauncher at all :)
I found only 2 exe files in root directory. 
REDprelauncher.exe - will run the game, when entering "My Rewards" - same story "Open game via GOG 2.0"
setup_redlauncher.exe - i guess main problem is here, REDprelauncher.exe tries to install REDLauncher and fails, when manually started it - it's just fail.
All that new stuff with REDLauncher is a pure mess. Before next-gen update i could easily transfer saves. I guess i will just leave that idea of crossplatform saves (and probably Witcher 3 with it :)). 
Thank you for your time.

**Comment by imLinguin** [comment]
> All that new stuff with REDLauncher is a pure mess  

Couldn't agree more. There shouldn't be any secondary launcher in the first place.  
I believe passing the `--launcher-skip` parameter will make it run the game exe directly, nevertheless the crossplatform saves and "My Rewards" won't work as they are now fully dependant on the REDLauncher.

Since it's now out of Comet scope I'll close this issue
