### ISSUE TITLE
Current compatibility

### ISSUE THREAD

**Issue by purplebar0** [imLinguin/comet#2]
Hi! I wanted to test Comet in its current state with games installed using [nicohman/wyvern](/nicohman/wyvern).

Obtaining access token, refresh token (using underscore in README.MD, please fix) and user ID was easy enough reading `~/.config/wyvern/wyvern.toml`, which worked:

```
INFO:comet_main:started listening on port 9977
```

However, starting a game (Cyberpunk 2077) gave the same results as Comet not running. This leads me to believe the launcher is also involved in establishing a session.

Will it be possible to play without a launcher? Have I made a mistake in testing?

**Comment by imLinguin** [comment]
You need to make sure the tokens are refreshed (for example by using sync command). Is there any output after you run Cyberpunk? Keep in mind games establish the connection at the start or in the game menu, so comet needs to run beforehand.

**Comment by purplebar0** [comment]
Update: Using the same token combination as in May 24th, I tested Cyberpunk 2077 (no console output from Comet), Firewatch (no console output from Comet, attempted to unlock an already unlocked achievement) and Absolute Drift. Absolute Drift was the exception, it attempted to initiate a connection, but crashed Comet in doing so.

```
INFO:comet_main:started listening on port 9977
41173
Accepting connection
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('0.0.0.0', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/serg/builds/comet/comet/main.py", line 86, in <module>
    asyncio.run(con_handler.handle_connection())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/serg/builds/comet/comet/handlers.py", line 90, in handle_connection
    await self.notification_pusher.setup()
  File "/home/serg/builds/comet/comet/api/notification_pusher.py", line 34, in setup
    self.connection = await self.session.ws_connect(self.url)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/lib/python3.11/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host notifications-pusher.gog.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fdf9dddd850>
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fdf9dddd990>
```

Note: I made sure the game versions are all for Windows.

**Comment by imLinguin** [comment]
That issue with SDK not connecting sounds new, I'll try looking into that. Maybe games look for some registry keys before initializing the SDK or just try different ports before. 

For leaderboards in Absolute Drift, issue like this is to be expected since we are still missing LEADERBOARDS_BY_KEY request.

**Comment by purplebar0** [comment]
As for Cyberpunk 2077, I took a look at [a list of parameters](https://pastebin.com/jmGpVNWe) extracted from the game executable and `-gameServicesWrapper ?` seems to be argument to look into for that specific game.

**Comment by imLinguin** [comment]
The parameter isn't used by Galaxy nevertheless, if you take a look at `goggame-GAMEID.info`, you'll see what's being passed in

**Comment by purplebar0** [comment]
> The parameter isn't used by Galaxy nevertheless, if you take a look at `goggame-GAMEID.info`, you'll see what's being passed in

True, but passing a dummy value makes a significant difference; just by looking at the main menu, "GOG rewards" tries to load instead of giving a warning, and cloud sync doesn't report an error (even though it should). I feel like it's worth testing.

**Comment by imLinguin** [comment]
Cross platform cloud sync in CP and the Witcher works, it's just not handled by SDK, but the game itself (only requiring authorization)

**Comment by kevin-wijnen** [comment]
Can +1 the issue of some games not interacting with Comet, illustrated with two other games on a system running Linux, playing the games through Valve's Proton tool:

- **Cuphead** (with the latest DLC installed) doesn't seem to connect with Comet, as it's stuck on `Waiting for a connection`. This game does have Achievement support, and earning the first achievement (by beating a boss) doesn't do anything, sadly.
- **Bug Fables: The Everlasting Sapling** does connect with Comet, but immediately gives an SSL certificate "Can't verify the local issuer certificate" error. (Will investigate this issue further in case I can find a remedy for it.)

**Note**: I did encounter this issue on a non-standard system (Steam Deck), running Comet through a PyInstaller-packaged version. I will make a Pull Request to have GitHub Actions auto-publish Steam Deck-compatible builds (as Steam Decks can't install Python-related dependencies etc. without unlocking the root filesystem, which in turn can get wiped after an update making unlocking it an unsuitable long-term solution to use Comet in combination with Heroic).

**Comment by imLinguin** [comment]
Going to close this now.. I'll look into having an automatic import of the auth from wyvern to further ease the usage with it.

In an event of compatibility issues with any games please make separate issues accordingly
