### ISSUE TITLE
Can't build on nixos, protoc not found

### ISSUE THREAD

**Issue by cronyakatsuki** [imLinguin/comet#22]
Hello, I have been trying to build comet rust rewrite on nixos and haven't been able to.

The problem is the protoc binary not working on nixos, so I have been trying to force the build script to use the one from nixos with no luck.

Is there any way to set a way to force a custom protoc binary with an environmental variable?

> Build error in question:
```
       >   process didn't exit successfully: `/build/source/target/release/build/comet-85bbf36aabd27783/build-script-build` (exit status: 1)
       >   --- stderr
       >   codegen failed: parse and typecheck
       >
       >   Caused by:
       >       0: using protoc parser
       >       1: failed to spawn command `"/build/cargo-vendor-dir/protoc-bin-vendored-linux-x86_64-3.0.0/bin/protoc" "-Iproto" "--descriptor_set_out=/build/protobuf-parseAZvrrH/descriptor.pbbin" "--include_imports" "proto/gog.protocols.pb.proto" "proto/galaxy.protocols.webbroker_service.proto" "proto/galaxy.protocols.overlay_for_peer.proto" "proto/galaxy.protocols.communication_service.proto" "proto/galaxy.common.protocols.peer_to_server.proto" "proto/galaxy.common.protocols.peer_to_peer.proto" "proto/galaxy.common.protocols.peer_common.proto" "proto/galaxy.common.protocols.connection.proto"`
       >       2: No such file or directory (os error 2)
```

I already tried to force it to use a different protoc binary with no luck.

This is my current nix derivation for it so if somebody with nix knowledge sees this might be able to do it:

```nix
{ pkgs, ... }:
with pkgs;
rustPlatform.buildRustPackage rec {
  pname = "comet-gog";
  version = "e313c8a";

  src = fetchFromGitHub {
    owner = "imLinguin";
    repo = "comet";
    rev = "62bcdd89d09d914edec6d2201891f292527d7b28";
    hash = "sha256-CZDx5vgWuG58yaoVvbfOASoULM1HnQxTmVWLa63ci9Q=";
    fetchSubmodules = true;
  };

  PROTOC = "${protobuf}/bin/protoc";
  PROTOC_INCLUDE = "${protobuf}/include";
  nativeBuildInputs = [ protobuf ];

  cargoLock.lockFile = src + /Cargo.lock;
}
```

**Comment by cronyakatsuki** [comment]
> You can try to adjust the `build.rs` file, namely remove the `protoc_path` line.

Yes by having made a simple patch file that removes the `protoc_path` line from build.rs and running it on latest commit it builds and works without issues.

Is there a possibility to have `build.rs` detect if a `PROTOC` environmental variable set so it sets `protoc_path` line to that path, so that there is no need to patch `build.rs` to have it build on distros like nixos?

**Comment by imLinguin** [comment]
Yes, I'll see if I can add it later this week

**Comment by imLinguin** [comment]
Hey, just pushed changes that should address this. Let me know

**Comment by cronyakatsuki** [comment]
> Hey, just pushed changes that should address this. Let me know

The new changes address this issue, can build without any problem on latest commit and without my hacky patch.

Tnx for fast fixing of the issue!
