### ISSUE TITLE
Online Multiplayer Compatibility Information

### ISSUE THREAD

**Issue by kevin-wijnen** [imLinguin/comet#28]
As I've not seen it mentioned here anywhere yet, except for tangentially related questions (for #11 and #14):

Is there any information available on GOG Galaxy's multiplayer capabilities being compatible with Comet instead of GOG Galaxy (i.e. _No Man's Sky_)? Or is that out of scope for the project?

**Comment by imLinguin** [comment]
It's safe to assume that multiplayer will work everywhere where it's implemented. Related features are handled by the SDK itself and work after the initial authorization call to comet.

**Comment by EthanHarp** [comment]
I was wondering if there were any plans to implement the encrypted_auth_ticket api?

**Comment by imLinguin** [comment]
if you mean this https://docs.gog.com/sdk-encrypted-tickets/?h=encrypted#retrieving-the-encrypted-app-ticket

I believe that works without communication service involvement

**Comment by EthanHarp** [comment]
Ah understood, thanks

**Comment by kevin-wijnen** [comment]
Getting back to this after having bought *No Man's Sky* on GOG: multiplayer definitely seems to work! I think the issue might better get closed then; with perhaps a pin in case others have a question about multiplayer support.

**Comment by kevin-wijnen** [comment]
Including reference to this issue as well #36:

Since `0.1.1`, more games are working with online multiplayer (in particular: those using OpenID).

**Comment by szszoke** [comment]
I have been using comet with No Man's Sky on both a Steam Deck and a desktop PC and it seems to work fine.

I was able to see other players on the Anomaly, see their chat, my achievement and play time also registered.

I used the shortcut script from the Steam Deck instructions.

**Comment by ssokolow** [comment]
One thing that I think could use a FAQ entry is whether it's possible to implement an offline/LAN-only fake of the GALAXY matchmaking servers for games like Dungeons 2 where some people got used to having a non-GALAXY, LAN-based multiplayer option and then the devs patched it out.

Currently, attempts to search for such a thing lead to announcements for Comet and then eventually to here.

(Note that I personally don't need the rest of what Comet does because it's already work enough to use stuff like Firejail or router-level firewalling to make sure my GOG downloads aren't secretly bearing archival time-bombs like "crash if we can't connect to Unity analytics".)

**Comment by imLinguin** [comment]
I think what you are looking for is https://github.com/grasmanek94/UniverseLAN

However it seems that Dungeons 2 has custom implementation for networking, thus making it impossible to force LAN

Comet acts more like GOG Galaxy for games and handles high level things: authorization, loading leaderboards etc... while the game's SDK does the actual heavy lifting.

**Comment by ssokolow** [comment]
Thank you. Even if it doesn't fix Dungeons 2, having that answer here is helpful to anyone who winds up walking the same path I did to find an answer.

Do you know if anyone maintains a list of GOG games which use UniverseLAN-incompatible netplay implementations?

**Comment by imLinguin** [comment]
Readme has that list. Includes both games that do work and those that don't
https://github.com/grasmanek94/UniverseLAN?tab=readme-ov-file#list--status-of-games
