### ISSUE TITLE
Achievements reported as being unlocked 3 hours earlier

### ISSUE THREAD

**Issue by wins1ey** [imLinguin/comet#29]
**Describe the bug**
Each time I unlock an achievement in the Witcher 3: Wild Hunt, they show up in my activity on gog.com as being unlocked 3 earlier than they actually were. I have only had my game open for 30 minutes, so its not using the time I opened the game.

**To Reproduce**
1. Unlock an achievement in a game
2. Go to https://www.gog.com/feed
4. See time

**Expected behavior**
It should correctly show how long ago I unlocked the achievement.

**System (please complete the following information):**
 - OS: Arch Linux
 - Kernel: Linux 6.9.4-arch1-1
 - Architecture: x86_64
 - Time zone: Europe/London

**Additional context**
![image](https://github.com/imLinguin/comet/assets/34382191/0fba6293-adb2-4775-9159-da76aa2a9fd4)

**Comment by imLinguin** [comment]
Comet reports the unlock time properly. It's the micro-service responsible for this particular feed that's wrong. 
You can compare it with the feed available in GOG Galaxy.

See https://github.com/imLinguin/comet/issues/21#issuecomment-2067338540

**Comment by wins1ey** [comment]
Ah okay, makes sense.

**Comment by Arcitec** [comment]
@imLinguin Wait, are you saying that GOG Galaxy + Comet handle the achievement timestamps correctly. But that the GOG.com website is the wrong one?

The GOG website is currently showing that I unlocked achievements "3 hours ago" when I unlocked it 1 hour ago, for example.

So there's no bug in Comet? It's a bug in GOG's website?

**Comment by imLinguin** [comment]
Yes, it's a gog website issue

**Comment by Arcitec** [comment]
@imLinguin Ah okay. Thanks a lot! I am loving Comet and the improved integrations with GOG. You're really starting to make GOG my favorite store thanks to Heroic and Comet. :)
