### ISSUE TITLE
Lack of artifacts and non-hidden text in Releases

### ISSUE THREAD

**Issue by kevin-wijnen** [imLinguin/comet#32]
Congratulations with putting out the first release (0.1.0) of Comet! 👏

**Is your feature request related to a problem? Please describe.**
The first & latest release of Comet lacks any artifact to download or any (immediately viewable) text for a change log. This hinders users who are not well versed in any Git repository hosting environment how to download the artifacts manually from the CI solution (GitHub Actions), or how to read a change log (by reading commit messages that were merged for said release).

**Describe the solution you'd like**
Either manually create releases with the Actions artifacts from said release attached, along with a change log (possibly derived from the merged commit messages). Or automate it through a GitHub Action.

**Describe alternatives you've considered**
Regarding automation - [there is a (still maintained) GitHub Action](https://github.com/softprops/action-gh-release) that could handle releases automatically by packaging artifacts of tagged releases.

**Additional context**
[GitHub used to host an own developed Action](https://github.com/actions/create-release) for this type of task - but this has been discontinued since 2020. Another possibility could be building something of our own to handle the API requests necessary to achieve such automation.

**Comment by imLinguin** [comment]
I have that automated, I'm just writing a nice release notes, so bear with me please. :smile:
