### ISSUE TITLE
Support *extremely rare* games using the GOG Linux SDK

### ISSUE THREAD

**Issue by cybik** [imLinguin/comet#33]
**Is your feature request related to a problem?**
No, it is only to bring attention to a very rare edge-case: some GOG games obtained through GOG may be bunding the "steam runtime" native Linux variant of the Galaxy libraries.

The ONE example I have of this is Indivisible. I know of it because I'm the one who bundled it for all platforms, and I insisted on having the Linux native libraries in place "just in case CDPr ever launched Galaxy on Linux". We can all guess how that turned out.

**Describe the solution you'd like**
***If necessary***, a native GalaxyCommunication "service" binary for Linux would be nice.

**Describe alternatives you've considered**
This ticket is only to raise the issue. I haven't considered anything.

**Additional context**
The current state of the Linux Native bits will require someone to have access to [GOG DevPortal](https://docs.gog.com/sdk/).

**Comment by kevin-wijnen** [comment]
Hey there - have you seen the current (for Windows version of games) [here](https://github.com/imLinguin/comet/issues/9#issuecomment-2028861414) solution already? This seems similar - except for this case focusing on Linux-native binaries. Some Windows games (i.e. Cuphead) even rely on a very old SDK of GOG that needed a dummy Communication Service binary to get working. Although most Windows games (and even few Linux native ones - like Stardew Valley and Crypt of the NecroDancer) work fine without the dummy service at the moment.

Not sure if there's any way to adopt the information @imLinguin learned for the Windows dummy binary could be used for a Linux native binary.

Are there any other known games that have the same situation as Indivisible?

(Also - thanks for packaging Indivisible back then for all bundles and keeping Linux support in mind. 🫡)

**Comment by imLinguin** [comment]
Thanks for bringing this up!  
Like @kevin-wijnen said we had some luck with native games here. To the mentioned list I'd like to add `Streets of Rage 4`.

I've researched this topic a bit, the requirement for having a `GalaxyCommunication` service. In fact the feature of SDK actually checking for that service was introduced in newer versions and is there to reduce delays in game launch when there nothing listens on the communication port.  

As far as I know it's no longer possible to access Linux native stuff through DevPortal.  
Out of curiosity I'll test the Indivisible

**Comment by cybik** [comment]
> Hey there - have you seen the current (for Windows version of games) solution [here](https://github.com/imLinguin/comet/issues/9#issuecomment-2028861414) already?

@kevin-wijnen I pointed it out in the ticket description, but basically, yes it would:
>  If necessary, a ***native*** GalaxyCommunication "service" binary for Linux would be nice.

@imLinguin re:
> As far as I know it's no longer possible to access Linux native stuff through DevPortal.

That's not what I'm seeing. Somehow my access is still valid, and going under "GOG Galaxy Components" and into SDK, `steam-runtime` is present. It's quirky and they're being VERY coy about Linux binaries, like, ***existing***, but the binaries are there. The issue here is whether they do anything at all or are mere shims - I never tested that.

**Comment by cybik** [comment]
For the record (can't believe I'm opening the data after all this time), the GOG variant was intended to be DRM-free.

In other words, if the GOG Galaxy desktop client (or its replacement) isn't there, the game code goes "meh" and plays the game all the same, but it ***does*** try to initialize GOG via the galaxy library.

So in a way, we don't need the shim service (I updated OP to point out *if necessary* just now); I mostly opened this ticket to make sure that the rare instances of native Linux games with *native Linux Galaxy libs* would not be forgotten.

**Comment by cybik** [comment]
Came back to add:

At the very least, `comet` as it is right now can actually yell achievements back to GOG. I just checked and cleared one!

**Comment by kevin-wijnen** [comment]
That's great! Definitely consider filling out a [Game Compatibility form](https://github.com/imLinguin/comet/issues/new?assignees=&labels=compatibility&projects=&template=compatibility.md&title=) to get it on the list!

**Comment by imLinguin** [comment]
Checked that as well, was able to unlock 2 achievements 
![obraz](https://github.com/user-attachments/assets/bdf08172-e886-4d4b-8678-f88843c1277c)

**Comment by cybik** [comment]
On my side it didn't manage to track play time. Not sure why.

**Comment by imLinguin** [comment]
Playtime isn't handled by comet unfortunately. At the moment Heroic Games Launcher does the tracking

**Comment by imLinguin** [comment]
Created a wiki page for game developers to refer to in regards of Linux native SDK  
https://github.com/imLinguin/comet/wiki/For-Game-Developers

**Comment by cybik** [comment]
All right then, at this point I think I can consider this closed.

And good stuff on the presentation at Ubuntu Summer '24!
