### ISSUE TITLE
Refuse to download `desktop-galaxy-overlay` for Linux

### ISSUE THREAD

**Issue by cybik** [imLinguin/comet#35]
**Describe the bug**
`comet` allows its Linux runtime to download the Galaxy overlay.

**To Reproduce**
1. Run Comet's Linux binary with the right tokens, and trigger the `overlay` command

**Expected behavior**
If the comet runtime is running on Linux natively, it could be assumed that the intended platform is Linux, not Windows. Since there is *no GOG Galaxy Overlay for Linux at present*, it should either refuse to download it, explicitly demand that its counterpart (in this case, let's say, Heroic would be calling comet) explicitly tell it that Windows binaries are expected/wanted/requested, or clearly default to Windows with either a confirmation or a clear label that "this platform does not have a native overlay, but there's Proton so here is the other guy".

**System (please complete the following information):**
 - OS: Linux
 - Architecture: x86_64

**Additional context**
This is probably the height of pedantry.
* If `comet` is run as a native Linux intermediary via Heroic or Lutris, but the game is a Windows game, then yes, downloading the overlay makes sense
* If `comet` is run as a native Linux intermediary for Linux-native GOG games, someone runs `comet overlay`, without any information to the contrary, the gamer could be made to assume the overlay will work with their native game.

It's an issue of communicating what's happening more clearly, in this case. Sorry for being *excruciatingly* pedantic about this one.

**Comment by imLinguin** [comment]
Added the following message when trying to run overlay command on Linux

```
[2024-08-20T10:25:56Z ERROR comet] There is no linux native overlay, to download a windows version use --force
```

**Comment by cybik** [comment]
Beyond satisfactory. Considering this addressed, thanks!
