### ISSUE TITLE
Lutris moved cache dir

### ISSUE THREAD

**Issue by stop5** [imLinguin/comet#37]
**Is your feature request related to a problem? Please describe.**
Im using a tmpfs for my cache dir and lutris uses that as default for writing the tokens in it.

**Describe the solution you'd like**
i saved the location in the ~/.config/lutris/lutris.conf in the lutris section in cache_dir, so it would be possible to read that path and use that as the cache dir for the token

**Describe alternatives you've considered**
Creating a symlink from .cache/lutris to my cache dir on each boot before comet starts

**Comment by imLinguin** [comment]
Hey, let me know if the solution works, consider testing the build from main branch https://github.com/imLinguin/comet/actions/runs/9927580824

**Comment by stop5** [comment]
Thanks. It works as intended
