### ISSUE TITLE
Enhance Comet Startup by Monitoring Heroic and Game Launches

### ISSUE THREAD

**Issue by RubenKelevra** [imLinguin/comet#39]
**Is your feature request related to a problem? Please describe.**
I followed the installation instructions and was curious: why do we need to add a script to Heroic to detect when a game starts?

**Describe the solution you'd like**
How about running a small service that first checks for Heroic's startup and then monitors game startups via the [fanotify API on the Linux Kernel](https://man7.org/linux/man-pages/man7/fanotify.7.html)? This service could subscribe to execution events, so when Heroic and subsequently a game launches, the `FAN_OPEN_EXEC` event triggers, allowing Comet to automatically start for the game.

**Comment by imLinguin** [comment]
Comet is designed to be managed by each game client. Although your suggestions is valid. 
There is a pull request in Heroic integrating comet for all GOG games https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3727
with that no manual steps will be necessary

**Comment by RubenKelevra** [comment]
Yeah read that, that's so great!
