### ISSUE TITLE
Game Compatibility: DOOM + DOOM II

### ISSUE THREAD

**Issue by kevin-wijnen** [imLinguin/comet#41]
**Game**  
- Title: [DOOM + DOOM II](https://www.gog.com/game/doom_doom_ii) 
- GOGDB: https://www.gogdb.org/product/1317223010

**Supported features**  
- [ ] Leaderboards
- [X] Achievements
- [X] Multiplayer

**Linux**  
- [ ] Linux build is available for the game
- [ ] Linux build supports Galaxy features

**Additional notes**  
Running on an older version of Comet on my main PC, but achievements seem to work just fine for DOOM I + II! :) Tested with Valve's Proton Experimental. Game version is `Version 2265 - 8/7/2024`.

![image](https://github.com/user-attachments/assets/6e97454d-5dfa-4d41-a647-87868b35a66b)
![image](https://github.com/user-attachments/assets/14eb57d7-932d-4e74-8c06-d9473c98bd4d)
---
Multiplayer is handled by Azure Playfab, and thus involves [the OpenID issue](https://github.com/imLinguin/comet/commit/ba57bb1f0a637453d57588fb7a2076edd0d0d3d5) (displaying "One or multiple accounts failed to sign in) if you run on an older Comet version, that got fixed before its first stable release. Updating to the latest release (` v0.1.2`) fixes this issue.

Cross-platform multiplayer works (Steam vs GOG tested):
![image](https://github.com/user-attachments/assets/e7344387-5ea1-4515-935d-97251c9d0bd4)

(It used different drivers for LAN play - this works cross-platform for PC platforms at the very least, tested by running the GOG version via Heroic and Comet, and the Steam version on the same Steam Deck.)
![image](https://github.com/user-attachments/assets/54698752-f8f2-4f82-a37a-cc0a2d143327)
_To launch the Console, press the ` ~` key on a keyboard._

**Comment by kevin-wijnen** [comment]
Table for convenience:

|[DOOM + DOOM II](https://www.gog.com/game/doom_doom_ii)|4.1.0-b5142 (4/3/2024)|🔲 Not Available|[version `v0.1.2`](https://github.com/imLinguin/comet/releases/tag/v0.1.2)|🔲 No|🟩 Achievements 🟩 Multiplayer|Achievements & Multiplayer do work as of `v0.1.2`.|

**Comment by imLinguin** [comment]
Awesome, thanks for testing!

**Comment by imLinguin** [comment]
@kevin-wijnen are you able to confirm the Bethesda.net linking works only with comet?

**Comment by kevin-wijnen** [comment]
> @kevin-wijnen are you able to confirm the Bethesda.net linking works only with comet?

Good that you mentioned it as I forgot to check:

- Logging into Bethesda.net *froze* the game **without** comet
- **Running with comet** and logging into Bethesda.net, it did *log in successfully*, as seen below:
    ![image](https://github.com/user-attachments/assets/e34f19f6-cc47-4b53-a8bc-572fdb9b3995)

After having successfully logged into Bethesda.net with comet and then proceeding to run without comet, the game seems to still recognise the Bethesda.net account and is able to browse player uploaded mods, download and play them just fine.

The only bug I noticed when *not* running comet (after an initial successful login), is that browsing "featured mods" is not possible and shows a "There was a problem retrieving the mods list. Please try again." error screen. Possibly to "safeguard" some mods from working with possibly pirated copies?
![image](https://github.com/user-attachments/assets/e9ebea96-f1d7-445d-a39d-7e766eddd7de)
