### ISSUE TITLE
Game compatibility: Metal Slug

### ISSUE THREAD

**Issue by mrcaique** [imLinguin/comet#43]
**Game**  
- Title: [Metal Slug](https://www.gog.com/en/game/metal_slug)
- GOGDB: [https://www.gogdb.org/product/1136471182](https://www.gogdb.org/product/1136471182)

**Supported features**  
- [x] Leaderboards
- [x] Achievements
- [x] Multiplayer

**Linux**  
- [ ] Linux build is available for the game
- [ ] Linux build supports Galaxy features

**Additional notes**  
This game do have Linux and macOS builds, but are legacy versions without the Galaxy features and are bundled as goodies (the same applies to the every other game in the Metal Slug bundle: Metal Slug 2, Metal Slug X and Metal Slug 3). 

I tested the Windows version using Valve's Proton 8.0, game version is `Version gog-3 - 26/05/2017`.

<details>
<summary>Leaderboards</summary>
<IMG src="https://github.com/user-attachments/assets/f541d0a8-50b4-40df-b8d3-31b607348033" alt="metal_slug_leaderboards"/>
</details>

<details>
<summary>Achievements</summary>

```
[2024-08-13T04:31:04Z INFO  comet::api::handlers::communication_service] Unlocking achievement MS1_009, 200 Tombs
[2024-08-13T04:31:14Z INFO  comet::api::handlers] Uploading new achievements
[2024-08-13T04:31:14Z INFO  comet::api::handlers] Uploaded achievements
```

<IMG src="https://github.com/user-attachments/assets/a52d88bc-b153-4271-8d90-b6cba054e311" alt="metal_slug_achievements"/>
</details>

I could not test the multiplayer component since none of my friends have this game on GOG. If anyone have it and are willing to test it, let me know.

<details>
<summary>Table</summary>

|Game Title|Game Version|Native Linux Version Works|Comet Version|GalaxyCommunication.exe Service Required|GOG Galaxy Features|Notes|
|-----|-----|-----|-----|-----|-----|-----|
|[Metal Slug](https://www.gog.com/en/game/metal_slug)|`Version gog-3 - 26/05/2017`|🔲 Not Available|[`v0.1.2`](https://github.com/imLinguin/comet/releases/tag/v0.1.2)|🔲 No|🟩 Achievements 🟩 Leaderboard|Achievements and leaderboard do work as of `v0.1.2`. Multiplayer not tested yet.|

</details>

If this information is enough, I can add it to the wiki. I will test the other games in the bundle (MS2, MSX and MS3) later and show the reports in their respective issues.

**Comment by imLinguin** [comment]
Sounds good! Thanks for testing and reporting it here
