### ISSUE TITLE
Duck Detective: The Secret Salami

### ISSUE THREAD

**Issue by mainrs** [imLinguin/comet#55]
**Game**  
- Title: Duck Detective: The Secret Salami
- GOGDB: https://www.gogdb.org/product/1280900495

**Supported features**  
- [ ] Leaderboards
- [x] Achievements
- [ ] Multiplayer

**Linux**  
- [x] Linux build is available for the game
- [ ] Linux build supports Galaxy features

**Additional notes**  
In these cases where the Linux build does not support Galaxy features (no Galaxy Unity plugin alongside installed files), can `comet` even work for these titles? Because I had it running and it did not register the achievements I got. 

__Edit:__ I just started the windows version installed via Lutris and their now is console output related to the game. I see a database setup message as well as sync messages for leaderboards. Yup, and the achievement got registered.

**Comment by imLinguin** [comment]
> In these cases where the Linux build does not support Galaxy features (no Galaxy Unity plugin alongside installed files), can comet even work for these titles?

It all depends if game was made with that in mind. The [dedicated wiki page](https://github.com/imLinguin/comet/wiki/For-Game-Developers) briefly describes what developers need to do to support that. 

Like mentioned in #33 there are a few games that are working. Just like the ones listed on [compatibility page](https://github.com/imLinguin/comet/wiki/Game-Compatibility)
