### ISSUE TITLE
SSL Certificate Verification error

### ISSUE THREAD

**Issue by kevin-wijnen** [imLinguin/comet#8]
When running Windows-based games through Proton (tested on 7.0 and Experimental) via the Heroic launcher, the following error tends to happen:

```
1)(deck@steamdeck comet_pyinstaller_version)$ ./main --from-heroic
INFO:comet_main:started listening on port 9977
INFO:comet_main:waiting for connection
45925
Accepting connection
Traceback (most recent call last):
  File "aiohttp/connector.py", line 980, in _wrap_create_connection
  File "asyncio/base_events.py", line 1050, in create_connection
  File "asyncio/base_events.py", line 1080, in _create_connection_transport
  File "asyncio/sslproto.py", line 529, in data_received
  File "asyncio/sslproto.py", line 189, in feed_ssldata
  File "ssl.py", line 944, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify 
failed: unable to get local issuer certificate (_ssl.c:1131)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 87, in <module>
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 616, in run_until_complete
  File "comet/handlers.py", line 91, in handle_connection
  File "comet/api/notification_pusher.py", line 34, in setup
  File "aiohttp/client.py", line 779, in _ws_connect
  File "aiohttp/client.py", line 536, in _request
  File "aiohttp/connector.py", line 540, in connect
  File "aiohttp/connector.py", line 901, in _create_connection
  File "aiohttp/connector.py", line 1206, in _create_direct_connection
  File "aiohttp/connector.py", line 1175, in _create_direct_connection
  File "aiohttp/connector.py", line 982, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host 
notifications-pusher.gog.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CE
RTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer cer
tificate (_ssl.c:1131)')]
[14660] Failed to execute script 'main' due to unhandled exception!
```

This has been tested on several games:

- [Cuphead](https://www.gog.com/en/game/cuphead)
- [Bug Fables: The Everlasting Sapling](https://www.gog.com/en/game/bug_fables_the_everlasting_sapling)
- [Absolute Drift](https://www.gog.com/en/game/absolute_drift)
- [FTL: Advanced Edition](https://www.gog.com/en/game/faster_than_light)

The Windows versions of these games running will give the SSL certificate verification error from the get-go.

If any further testing is needed for debugging, please let me know. I'll happily cooperate to get this sorted.

**Note:** This is done on a PyInstaller-packaged version of Comet as I try to make it compatible for Steam Deck users via Heroic. See #9.

**Comment by imLinguin** [comment]
This sounds like some more complex issue. And has nothing to do with games being Windows versions or not.

**Comment by kevin-wijnen** [comment]
> This sounds like some more complex issue. And has nothing to do with games being Windows versions or not.

Fixed the descriptions in both here and #9, because of the lack of GOG Galaxy SDK support for native Linux titles to begin with.

**Comment by imLinguin** [comment]
Does it change anything if you launch comet binary from flatpak container?
```
flatpak run --command=bash com.heroicgameslauncher.hgl
./path/to/comet --from-heroic
```

**Comment by kevin-wijnen** [comment]
I've just tried it, and it simply gives a `./<path>: ./<path>: cannot execute binary file`. Launching it separately does what is expected.

But this might be because of this issue with PyInstaller: https://github.com/pyinstaller/pyinstaller/issues/4242#issuecomment-495074358

**Comment by kevin-wijnen** [comment]
Update on the issue above:

Creating a bash (`.sh`) script and running that through bash with the `flatpak run` command solves the "can't execute binary" problem :
- `cd` into the directory that has the `comet` executable
- Running said `comet` executable with the `--from-heroic` flag

However, it still has the same `CERTIFICATE_VERIFY_FAILED` issue from before, making no difference compared to running it directly through bash itself.

Could it be related to the actual SSL certificates used by GOG? I recently tried to download my purchased Hellblade soundtrack from GOG and it gave me an SSL certificate warning I had to pass through on my Firefox browser before being able to download it.

Looking around, there is an article that uses an unverified context to bypass those types of errors. Maybe a flag could be made to bypass SSL certificate checks, as a workaround? https://support.chainstack.com/hc/en-us/articles/9117198436249-Common-SSL-Issues-on-Python-and-How-to-Fix-it

**Comment by kevin-wijnen** [comment]
# Update

The reason I might have been getting SSL certification verification errors, is potentially due to missing root certificates on the Steam Deck.

As I can not add certificates without opening the root filesystem (see #9 why that is not a good idea), I decided to have the Python code ignore SSL certificates by adding `verify_ssl=False` to every session call.

To be exact, I added `verify_ssl=False` to the following bits of code:

- `api/notification_pusher.py` --> line 34, after `self.url`, resulting in `self.connection = await self.session.ws_connect(self.url, verify_ssl=False)`
- `api/token.py` --> every instance of `session.get` or `session.delete`, adding `verify_ssl=False`, before the `)`.

Other Steam Deck specific issues and handling will be posted in #9 shortly.

# Warning
This workaround could pose as a **security risk** for people hijacking client information while they don't possess the right certificate on the endpoint. Without SSL verification working, a forged GOG connection could be created.

**Comment by imLinguin** [comment]
The other potential solution I see would be to ship those certificates from GOG Galaxy

**Comment by kevin-wijnen** [comment]
> The other potential solution I see would be to ship those certificates from GOG Galaxy

Fully agreed. I did not manage to figure out how to include own PEM certificates and have the application use them. Thus I went with the "disable SSL verification altogether" as a temporary workaround to get it in a bootable state on the device.

**Comment by imLinguin** [comment]
Should be resolved by rust rewrite, we are now shipping certs from GOG Galaxy
