### ISSUE TITLE
Steam Deck Compatibility

### ISSUE THREAD

**Issue by kevin-wijnen** [imLinguin/comet#9]
### Context

Steam Deck users can not easily use Comet due to SteamOS using an immutable filesystem. To allow Python's pip to be installed, users [would have to unlock the filesystem](https://help.steampowered.com/en/faqs/view/671A-4453-E8D2-323C). The changes made to said file system [could be wiped in a future update, making it unsuitable for long-term use](https://partner.steamgames.com/doc/steamdeck/faq#:~:text=we%20don't%20recommend%20this%20though%2C%20as%20they%20may%20get%20their%20steam%20deck%20into%20a%20bad%20state%20or%20compromise%20their%20data.%20in%20addition%2C%20anything%20installed%20outside%20of%20flatpak%20(via%20pacman%20for%20instance)%20may%20be%20wiped%20with%20the%20next%20steamos%20update.%20more%20on%20that%20here.).

### Proposal

To get around this issue, I have been tinkering with using [**PyInstaller**](https://pyinstaller.org/en/stable/usage.html) to package the application into a bootable executable for immutable file systems.

To get a bootable executable, do the following steps:
- Installing the requirements of Comet
- Moving the `api`, `classes`, `proto` folders and the `handlers.py` script into a single folder called `comet`
- Running `pyinstaller main.py`
- Go into the newly created `dist/main` folder, and simply run `./main`.

### Current Issues

While the application boots fine on Steam Deck by calling it with `./main --from-heroic`, it seems to currently fail at SSL Certificate verification (#8).

Once this issue has been resolved, I will create a Pull Request to deal with the GitHub Actions automation for building Steam Deck-compatible releases along with instructions how to use it on Steam Deck.

**Comment by imLinguin** [comment]
Hi, thanks for interest in the project. Steam Deck compatibility (rather it's lack) is currently intentional. As comet isn't feature complete yet and very unstable with connection issues.

About Linux games, there is nothing we can do, those games don't ship client library since Linux version it not provided by GOG.

I'll be looking forward to rewriting this in Rust for more robust error handling and better performance

**Comment by kevin-wijnen** [comment]
> Hi, thanks for interest in the project.

No problem! I stumbled upon this project today after searching if anyone got achievements working through Heroic, considering Cloud Syncing (and even playtime syncing with GOG got recently committed to Heroic) already was up and running with compatible games. Figured wanting to pitch in getting this to work for Steam Deck especially, as Heroic got a lot more attention through that device nowadays.

> About Linux games, there is nothing we can do, those games don't ship client library since Linux version it not provided by GOG.

I honestly didn't think of any absence of a GOG SDK for Linux, despite them not shipping a Linux client at all. Thanks for the reminder. Wouldn't be a huge issue for most games as they don't have native ports.

> I'll be looking forward to rewriting this in Rust for more robust error handling and better performance

Wishing you the best of luck with that! 👍As long as this Python version is still up and supported, I'll at least keep an eye out for any fixes regarding the SSL certificate (#8) issue and try to assist with it as much as I can (as I do lack any experience in Rust at the moment). Once that's resolved or not reproducible anymore and the basic features Comet implemented do work, then I'll go ahead and create the PR for the Deck compatibility despite the instability.

**Comment by imLinguin** [comment]
I believe for PyInstaller builds you can also run it like this:
```
pyinstaller --onefile --name comet --strip comet/main.py
```
Then you don't need to move everything to one file

**Comment by kevin-wijnen** [comment]
# Update: Steam Deck is capable of running the app after packaging it with PyInstaller.

I have tried once again to get the app working on the Steam Deck. After implementing a SSL verification ignoring workaround (as mentioned in #8), I have gotten the app to run. Although this does require some additional testing from me and potential other Steam Deck users to verify if the app is actually working as intended.

## How to get it to run on a Steam Deck
To make the app runnable on the Steam Deck without unlocking the root filesystem and installing Python on it (with the risk of getting wiped on a(n OS) update), I've opted for suggesting using a PyInstaller package to eliminate the need for installing Python altogether. It requires a Linux-based computer to pre-compile it, however.

On my end, I used **WSL2's Ubuntu** to package it with PyInstaller, with the following steps:

1. Install pip3 (`sudo apt-get install python3-pip`)
   > If the package is not found, do `sudo apt-get update` and `sudo apt-get upgrade` to update your system and the package list.
2. Install PyInstaller as root
   `sudo -i`
   `pip3 install PyInstaller`
   `exit`
3. Install the dependencies of the project
   `pip install git+https://github.com/imLinguin/comet.git`
   > This leaves the project installed on your system however. But this was for me the quickest way to have the dependencies installed for compilation. Otherwise used dependencies will NOT get included in the final PyInstaller package. 
4. Go into the `comet` directory in the project root directory and compile the PyInstaller package
   `pyinstaller --onefile --name comet --strip main.py`
5. Copy the `comet` executeable to your Steam Deck
   > Any file transfer service is usable. I personally used [Pairdrop](https://pairdrop.net/) on both my Windows PC and Steam Deck in the desktop mode browser to sent a zip file containing the executeable)
6. In Desktop Mode, open a Terminal in the folder the `comet` executeable is present at, and mark it as an executable
   `chmod +x comet`
7. Run the executable as normal
   > For this step, it's assumed to launch it the way as intended and presented in the README. Due to my working installation of the Heroic Launcher, I use the --from-heroic flag.
   `./comet --from-heroic`
8. Boot up a game that uses the GOG Galaxy SDK to communicate.

# Remaining Potential Issues
The only game I could've gotten to connect with, is [Bug Fables: The Everlasting Saplings](https://www.gog.com/en/game/bug_fables_the_everlasting_sapling) and [Yakuza 0](https://www.gog.com/en/game/yakuza_0). After opening a local webserver and waiting for connections, I boot up the game and it does the following:
- "notification_message:2|2"
- Subscribes to the chat, presence, friends
- Authenticates the user (with the correct GOG username)
- Proceeds to subscribe to the chat, friends and presence topics.

When sending chat messages to or receiving them from friends on GOG, the logger indicates it receives the Websocket messages just fine.

I have not gotten far enough in the game to actually unlock achievements.

Proceeding to try other games (Cuphead, Stonks 9000) which do advertise Overlay and Achievement support, neither of those two games (Windows versions) seem to connect at all with the GOG Galaxy SDK. 

**Is there a list of games which are verified to work with comet, for further testing?**

**Comment by kevin-wijnen** [comment]
@imLinguin Useful input regarding getting it to work on the Steam Deck - yet need more testing/information on how the actual application works in action regarding to achievements.

After I can confirm it works as intended with achievements etc., I will make a PR to apply my local-only Steam Deck-working changes along with documentation specifically for Steam Deck users.

**Comment by kevin-wijnen** [comment]
![afbeelding](https://github.com/imLinguin/comet/assets/58944808/4da4a9a2-6375-412a-b222-0ecd6ea68a60)

An additional screenshot, to show what happens after implementing the workaround mentioned in #8. This is the result I get when testing Bug Fables and Yakuza 0, but not with some other achievement compatible games such as Cuphead and Stonks 9000.

**Comment by imLinguin** [comment]
Let me know if any improvements are noticeable after Rust rewrite

**Comment by kevin-wijnen** [comment]
> Let me know if any improvements are noticeable after Rust rewrite

Thanks for reminding me about the Rust rewrite!

I got Comet working out of the box doing the following:

- Grabbing the latest CI/CD (Github Actions) release for x86_64)
- Made sure Heroic is still logged into GOG
- Extracted the .zip archive from the CI/CD into a separate folder (running it from a microSD card works just fine)
- Marked the executable (Right click on `comet` > Properties > Permissions tab > click the checkbox for `Is executable`) 
- Open Konsole (a terminal window) into the same direrctory where the `comet` binary resides
- Run the following command: `./comet --from-heroic --username <my username>` with `<my username>` replaced with my GOG username

It immediately listens to the websocket port 9977 on the Steam Deck, and successfully connects to the notifications-pusher of GOG.
Subscription requests run fine as well, subscribing to `chat`, `friends` and `presence`.

However, it seems to still fail to change the online status on GOG. I do get a warning (multiple times) stating `Failed to notify handlers about going online channel closed`. (Precisely every minute, it reattempts the process but it still gets the warning.)

Upon booting a supported game, it successfully communicates with the communication service and spits out Client identifiers and sets up a database in the `/home/deck/.local/shjare/comet/gameplay/<some type of ID?>/gameplay.db`.

After quitting supported games, it correctly closes the Client part of the websocket connection and sends the playtime properly to GOG. What I did notice, is that this was initially partially implemented with the Python version? GOG now properly says "<X> played for the first time" in the user profile activity.

Despite this, I still am not able to unlock achievements apparently with **Cuphead**. Cuphead for some reason seems to "avoid" comet, despite being a Windows game with GOG Galaxy SDK support in regards to achievements. Compared to Bug Fables and Yakuza 0, it doesn't start a session at all.

For **Absolute Drift** (the Windows version), it seems to capture the API calls to sending leaderboard stats, but fails with a 404 error for an URL, along with saying the request type was not implemented. Besides the errors in getting the GOG Friends and your own Leaderboard stats, **achievements seem to work!** I did notice Absolute Drift "uploading stats" quite often, and eventually also achievements. Although it didn't state which achievement had been unlocked (it happened to be the _Maverick_ achievement).

**Comment by kevin-wijnen** [comment]
If there's any more technical debugging needed - feel free to ask me, I'm happy to help.

I could if wanted start a Pull Request to include Steam Deck specific instructions on how to make it work on Game Mode. I only tested in _Desktop Mode_, but I assume a simple bash script linked with a non-Steam game shortcut should work getting it to run in the background on the Steam Deck's _Game Mode_.

**Comment by imLinguin** [comment]
Thanks for all this testing. The playtime is handled by Heroic itself as this is what manages games.

> Failed to notify handlers about going online channel closed

This line is to be expected when no games are connected. I'll probably move that message to the debug channel. (Which btw you can trigger by setting `COMET_LOG=debug` environment variable)

> Cuphead for some reason seems to "avoid" comet, despite being a Windows game with GOG Galaxy SDK support in regards to achievements.

This is good to know, I'll see if I can get that game and try this myself.

Message 37 refers to not yet implemented `SET_LEADERBOARD_SCORE` request. I'm on the right track on implementing this one and should have it done pretty soon.

> Although it didn't state which achievement had been unlocked (it happened to be the Maverick achievement).

I'll see if I can add some logging on that, ideally we should have some sort of overlay e.g by Decky Loader plugin (#18) or official Galaxy overlay (#17) to handle such notifications

> I could if wanted start a Pull Request to include Steam Deck specific instructions on how to make it work on Game Mode. I only tested in Desktop Mode, but I assume a simple bash script linked with a non-Steam game shortcut should work getting it to run in the background on the Steam Deck's Game Mode.

This would be nice to have, if you are willing to do it, you should be able to edit the dedicated wiki pages https://github.com/imLinguin/comet/wiki

**Comment by kevin-wijnen** [comment]
I will try to publish my findings in the wiki/in the temporary fork tonight or tomorrow, but TL;DR: **I got a barebones bash script working to run Comet along with any non-Steam game shortcut, with few modifications.** This script _does_ work on Game Mode!

--

> This line is to be expected when no games are connected. I'll probably move that message to the debug channel. (Which btw you can trigger by setting COMET_LOG=debug environment variable)

Thanks for the heads up, I added the option into my script to run a game shortcut and comet simultaneously. I'll see if I could get any worthwhile info out of games that aren't working well with Comet at the moment (i.e. Cuphead).

> This is good to know, I'll see if I can get that game and try this myself.

I'll see if I can set up some compatibility chart for the wiki as well. Although it'll take a while to go through games I got in my GOG library that has Galaxy Achievement support. Might be noteworthy that some games may have a different implementation due to [proxying Steamworks SDK calls](https://docs.gog.com/steam-sdk-wrapper/). Only games I did notice going with this approach are the **Yakuza/Like a Dragon** games, when looking at the files through [**gogdb**](https://www.gogdb.org/manifest/2eaa041001d51486c1e7b0d471fbf9f0) (see the `GalaxySteamWrapper64.dll` file).

> I'll see if I can add some logging on that, ideally we should have some sort of overlay e.g by Decky Loader plugin (https://github.com/imLinguin/comet/issues/18) or official Galaxy overlay (https://github.com/imLinguin/comet/issues/17) to handle such notifications

This would definitely be ideal. I reckon Decky Loader might be a suitable ecosystem to look into providing some type of notification system. You could look how other Decky plugins utilise Steam's toaster (notification) functionality for their own custom notifications. This could help out with achievement notifications.

**Comment by kevin-wijnen** [comment]
# Update

As you may have noticed, I just opened #19 with it adding the script I currently use with GOG games (e.g. Absolute Drift) to run Heroic shortcuts along with Comet for achievement and GOG time tracking support.

I'd highly recommend adding, after merging, the `comet_shortcut.sh` file and its `USAGE.md` file to the Linux builds' `.zip` files to simplify getting the script directly when downloading the build by changing the current GitHub Actions workflow.

**Comment by imLinguin** [comment]
Thanks for the Pull request.

> Although I would still highly recommend coming up with a "release strategy" to have builds easily downloadable on GitHub as a release, rather than having to look into the latest Actions run.

Absolutely, this is only temporary as I still want to iron things out before the initial release

Meanwhile I have found the solution for Cuphead, I will push relevant commits in a bit. Turns out more games may be affected as this is purely dependent on version of `Galaxy64.dll`

**Comment by kevin-wijnen** [comment]
> Meanwhile I have found the solution for Cuphead, I will push relevant commits in a bit. Turns out more games may be affected as this is purely dependent on version of `Galaxy64.dll`

Interesting. I did try disabling other DLLs (`GalaxyCSharpGlue.dll` and `GalaxyPeer.dll`) with Cuphead, as there were [reports of other games having issues with unlocking achievements because of `GalaxyCSharpGlue.dll`](https://www.reddit.com/r/HollowKnight/comments/137c055/psa_how_to_reenable_achievements_on_the_gog/).

Good to see you've found the actual culprit. Once the commits roll in, I'll sync the Pull Request and report back the results of Cuphead after testing it for myself as well.

**Comment by imLinguin** [comment]
Just pushed e313c8ae052dfd9a6b06c8246f83f5f34672bcaa  
I was able to successfully receive the request with this workaround. It feels kinda hacky, however Ideally Heroic, Lutris and other tools will set this up automatically. 

```
[2024-03-28T20:13:50Z INFO  comet::api::handlers::communication_service] Client identified as 50555459027037412 ce3ce00794309c249161c1175035225816fc21d423ca3de0dcc098685b685d70
[2024-03-28T20:13:51Z INFO  comet::db::gameplay] Setting up database at "/home/linguin/.local/share/comet/gameplay/50555459027037412/52382489165353163/gameplay.db"
[2024-03-28T20:14:05Z INFO  comet::api::handlers] Socket connection closed with Some("50555459027037412")
```

With this, the game coverage will be improved.

**Comment by kevin-wijnen** [comment]
> Just pushed [e313c8a](https://github.com/imLinguin/comet/commit/e313c8ae052dfd9a6b06c8246f83f5f34672bcaa) I was able to successfully receive the request with this workaround. It feels kinda hacky, however Ideally Heroic, Lutris and other tools will set this up automatically.
> 
> ```
> [2024-03-28T20:13:50Z INFO  comet::api::handlers::communication_service] Client identified as 50555459027037412 ce3ce00794309c249161c1175035225816fc21d423ca3de0dcc098685b685d70
> [2024-03-28T20:13:51Z INFO  comet::db::gameplay] Setting up database at "/home/linguin/.local/share/comet/gameplay/50555459027037412/52382489165353163/gameplay.db"
> [2024-03-28T20:14:05Z INFO  comet::api::handlers] Socket connection closed with Some("50555459027037412")
> ```
> 
> With this, the game coverage will be improved.

How do you fire a command at a Wine/Proton prefix managed by Heroic? Using [Protontricks](https://github.com/Matoking/protontricks), you can run a Wine cmd shell and then do the required service creation commands for this workaround.

To get to the Wine cmd shell, I did the following:

- Go to Heroic for a game's page
- Go to the game's settings
- Scroll down to find WINETRICKS and click on the button
- Once loaded in, click the OPEN WINETRICKS GUI button
- Select the `Install an Application` option, then cancel out of it
- Select the `Run a Wine cmd shell` option

While this process (starting from the Winetricks GUI) works on Protontricks (not for Heroic managed instances, however), it does not for Heroic as an error appears in the log window of Heroic (for Winetricks):

`Gtk-Message: <timestamp>: Failed to load module "canberra-gtk-module"`

This error currently prevents Heroic users on Steam Deck from accessing the Wine cmd to do this manually.

**Comment by imLinguin** [comment]
> How do you fire a command at a Wine/Proton prefix managed by Heroic? Using [Protontricks](https://github.com/Matoking/protontricks), you can run a Wine cmd shell and then do the required service creation commands for this workaround for prefixes managed by Steam itself.

I guess we can just make a .bat script to be ran using `Run exe in prefix` feature and make the instructions simple like to put the .exe into prefix's `system32`  
![obraz](https://github.com/imLinguin/comet/assets/62100117/2a069fee-1ca9-443d-a838-43b5771d3f00)

> And out of sheer curiosity, is the GalaxyCommunications dummy necessity possibly related to [the issue (nr. 14, about the GalaxyPeer.dll inclusion) mentioned in the public GOG Galaxy SDK documentation](https://docs.gog.com/faq/#general-sdk-questions)?

This is completely separate and we'll need to handle this accordingly as well. Although the lack of `GalaxyPeer.dll` in game files may hint that the game doesn't require the dummy service.

**Comment by kevin-wijnen** [comment]
> > How do you fire a command at a Wine/Proton prefix managed by Heroic? Using [Protontricks](https://github.com/Matoking/protontricks), you can run a Wine cmd shell and then do the required service creation commands for this workaround for prefixes managed by Steam itself.
> 
> I guess we can just make a .bat script to be ran using `Run exe in prefix` feature and make the instructions simple like to put the .exe into prefix's `system32` ![obraz](https://private-user-images.githubusercontent.com/62100117/317899843-2a069fee-1ca9-443d-a838-43b5771d3f00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NjY5NzQsIm5iZiI6MTcxMTY2NjY3NCwicGF0aCI6Ii82MjEwMDExNy8zMTc4OTk4NDMtMmEwNjlmZWUtMWNhOS00NDNkLWE4MzgtNDNiNTc3MWQzZjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDIyNTc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MzkyN2E3ZjIzNTMxY2M0MmM3ZjA2OTRhMzViNzkxYTI1ZTY3OWU0ODgwM2M5OGZlNGQzZmQyYTQzN2JmODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wfklhRkjPJJvblIbasiljDSUYvjbayBtGOihjf__I0Y)
> 
> > And out of sheer curiosity, is the GalaxyCommunications dummy necessity possibly related to [the issue (nr. 14, about the GalaxyPeer.dll inclusion) mentioned in the public GOG Galaxy SDK documentation](https://docs.gog.com/faq/#general-sdk-questions)?
> 
> This is completely separate and we'll need to handle this accordingly as well. Although the lack of `GalaxyPeer.dll` in game files may hint that the game doesn't require the dummy service.

Thanks for the proposed solution. I made a quick .bat script with the service creation command in it. Initially it didn't seem to work dragging it into the "Run .exe file in prefix". But after either doing it again or manually selecting the .bat file from the file picker (I don't know what did the trick, or if I simply wasn't paying enough attention initially), it seemingly worked! I managed to test it with Cuphead (latest version including DLC) and unlocked the simple "Defeat a Boss" achievement.

I'll attach a .bat file for common use (along with Heroic instructions in the USAGE.md for Steam Deck users), just to be safe. But that'll be for tomorrow.

I'd recommend using the proposed dummy file path in the documentation (the `ProgramData` path) as that would make it look a bit "cleaner" than just dropping it into system32. Could be done by simply recreating the folder structure and make it easy to copy-paste for any user. (Simply "Copy and paste this folder into the game prefix, and drag the .bat file into the Heroic's "run an .exe" box to make it work for older GOG Galaxy SDK titles) But which path eventually is chosen is subjective/not that important for functionality.

**Comment by imLinguin** [comment]
Sounds good, alternatively we can consider having the .bat doing the copying as well. Assuming the `GalaxyCommunication.exe` is next to the script. One less step for the end user to do. I imagine this makes it simpler for Lutris users as well

**Comment by kevin-wijnen** [comment]
> Sounds good, alternatively we can consider having the .bat doing the copying as well. Assuming the `GalaxyCommunication.exe` is next to the script. One less step for the end user to do. I imagine this makes it simpler for Lutris users as well

I just pushed my latest commit out to accomodate for the dummy service installation. For Linux artifacts, two more things will be now present in the artifact zip archive:

- The `.bat` script necessary to create the service with Heroic's `RUN EXE IN PREFIX` functionality (as documented in the USAGE.md for Steam Deck users as briefly touched upon in the dummy service's README.md).
- A recreated folder structure for the prefix, beginning with the `pfx` root folder that has the Galaxy Communication dummy located in (in the earlier proposed `ProgramData/GOG.com ...` file path, where the usual `GalaxyCommunication.exe` would be).

This allows Proton users to simply copy the `pfx` folder and have it write into the game's prefix `pfx` folder, and use Heroic to drag the `.bat` script over to install the service as required.

The CI has been adjusted to download the compiled dummy service, unzip it (as GitHub automatically zips artifacts) and properly place it in the recreated `pfx` directory.

**Comment by kevin-wijnen** [comment]
# Update

For anyone reading this, **the PR** created by me and helped by others (**#19**) **has been merged. 🎉**

**Most, if not all Linux or macOS (WINE/Proton managed) installs of a Windows game should now at least function** achievement wise. Some features may yet to be implemented (e.g. _leaderboard support_ with Absolute Drift). As the owner of the repository has stated before, the new addition of the `GalaxyCommunication.exe` dummy service expanded game compatibility with Comet for games that wouldn't try communicating with GOG services without such service (e.g. Cuphead).

Wanted to thank everyone who pitched in. I will try to continue to aid regarding Steam Deck compatibility in the future on my own initiative.

**Comment by imLinguin** [comment]
About Cuphead, I managed to register some achievements and clock in some playtime. All features used by the game seem to work. :tada: 

![image](https://github.com/imLinguin/comet/assets/62100117/0cf584b2-c3fb-4370-baf7-4162df6ddd9a)
![image](https://github.com/imLinguin/comet/assets/62100117/894494e1-6e54-4332-bfc0-7073ee25780e)

**Comment by italoghost** [comment]
Hi! I have been testing with Heroic Games + comet within a gamescope session. I would like to add some things that I have found:

1) As I run GNOME, I have changed the `comet_shortcut.sh` file, replacing
 ```
 konsole -e "$path_to_comet --from-heroic --username $gog_username" &
 ```
  
 to
  
 ```
 gnome-terminal -- $path_to_comet --from-heroic --username $gog_username &
 ```
  
but it didn't work! After debugging for some time, I realized that, for some reason, the `gnome-terminal` do not work within the gamescope session. Using another terminal emulator, like `gnome-console` or `alacritty` did the trick. 

2. Instead of adding the script to the launch options on Steam, I added them to the recently added "Scripts" option on Heroic:

![image](https://github.com/imLinguin/comet/assets/48540550/b513a3c7-5b47-4eab-ba7e-ff244b160bc8)

And created a second script to kill the comet process after 45 seconds. The script is as follows:

```
sleep 45 && kill -INT $(pgrep comet)
```

I am not experienced at all on scripting on Linux, but it was the least invasive way of automatically killing the process that I found. I am accepting suggestions if it is not ideal.

**Comment by kevin-wijnen** [comment]
Thanks for looking into getting the shortcut to  run on GNOME environments @italoghost! I honestly didn't think of using HGL directly to manage launching (and shutting down) Comet. (Mainly because using Steam's interface on the Steam Deck sounded more logical than using HGL's advanced options.)

Testing HGL's option to launch the script before the game however, I don't see any Comet window or anything indicating Comet is running in the background. How is Comet running on your system, when using said feature?

---

If it ends up working as a proper solution, I'd highly encourage making a Pull Request to add a GNOME version of the `comet_shortcut.sh` with additional instructions and requirements (I'm not sure if GNOME Console is pre-installed compared to GNOME Terminal?), including the Heroic Games Launcher steps.

I took a look at Lutris and in the System tab of any game (when toggling on Advanced Options), you can find similar functionality for launching the script (even specifying whether to wait for a script to finish before launching the game).

**Comment by kevin-wijnen** [comment]
> I believe we can adjust the scripts to use the `--quit` parameter introduced with [42768af](https://github.com/imLinguin/comet/commit/42768af2056c5bc8ed2e51f8ff6e933d8802fc5d) That will allow to remove need for terminal emulators completely.

Once the Nightly Build cycle passes, I'll test it on my desktop and Steam Deck. Will keep us all posted.

**Comment by italoghost** [comment]
> I believe we can adjust the scripts to use the `--quit` parameter introduced with [42768af](https://github.com/imLinguin/comet/commit/42768af2056c5bc8ed2e51f8ff6e933d8802fc5d) That will allow to remove need for terminal emulators completely.

Just tested it, adding `--quit` to the end of the string:

```
# Running Comet as a separate Konsole window
alacritty -e $path_to_comet --from-heroic --username $gog_username --quit &
```

It worked flawlessly!

**Comment by imLinguin** [comment]
I triggered the manual build just now

**Comment by italoghost** [comment]
> Thanks for looking into getting the shortcut to run on GNOME environments @italoghost! I honestly didn't think of using HGL directly to manage launching (and shutting down) Comet. (Mainly because using Steam's interface on the Steam Deck sounded more logical than using HGL's advanced options.)
> 
> Testing HGL's option to launch the script before the game however, I don't see any Comet window or anything indicating Comet is running in the background. How is Comet running on your system, when using said feature? **Edit: Seems like for some reason `konsole` is not detected as a command when Heroic tries to run the script.**
> 
> It's worth mentioning (for Flatpak users) that any user would need to either put the scripts into a directory HGL already has access to or specifically allow HGL to see the directory where the Comet scripts are (otherwise, HGL will only get a temporary file location that would break after subsequent uses). [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal) is an easy GUI tool to achieve this with.
> 
> If it ends up working as a proper solution, I'd highly encourage making a Pull Request to add a GNOME version of the `comet_shortcut.sh` with additional instructions and requirements (I'm not sure if GNOME Console is pre-installed compared to GNOME Terminal?), including the Heroic Games Launcher steps.
> 
> I took a look at Lutris and in the System tab of any game (when toggling on Advanced Options), you can find similar functionality for launching the script (even specifying whether to wait for a script to finish before launching the game).

When I closed the game, the terminal window with comet running would appear. I just checked with `htop` which process was running comet and added it to the "kill" script. I had the same "issue" as you: the terminal itself would not appear as a process, only comet. That is why I put `$(pgrep comet)`.

I will try to create a pull request as I learn how to use git.

**Comment by italoghost** [comment]
> I triggered the manual build just now

Just for recording, I am using [comet-gog-git](https://aur.archlinux.org/packages/comet-gog-git), from the AUR.

**Comment by kevin-wijnen** [comment]
Testing the new binary + editing my `comet_shortcut.sh`  to remove Konsole and rely on the `--quit` flag (along with removing the double quotes (") around `$path_to_comet [...] $gog_username &` to have it work through Heroic).

The logs of the game (Settings > Log > [Your played game's name]) contain the Comet logs too, which is perfect for now.
